# Copyright (c) Meng Hu
# Distributed under the terms of the Modified BSD License.
FROM jupyter/scipy-notebook

MAINTAINER Meng Hu <humeng1220@126.com>

USER root

RUN apt-get update && \
    apt-get install -yq --no-install-recommends \
    cmake \
    pkg-config \
    libatlas-base-dev \
    gfortran \
    libjasper-dev \
    libgtk2.0-dev \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    libjasper-dev \
    libv4l-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER $NB_USER

# Install numpy
RUN conda install --quiet --yes 'numpy=1.13.3'

# Install Python 2 numpy
RUN conda install --quiet --yes -n python2 'numpy=1.13.3'

RUN wget https://github.com/opencv/opencv/archive/3.3.1.tar.gz -O opencv.tar.gz && \
    tar -xf opencv.tar.gz

RUN wget https://github.com/opencv/opencv_contrib/archive/3.3.1.tar.gz -O opencv_contrib.tar.gz && \
    tar -xf opencv_contrib.tar.gz

RUN mkdir /opencv/build && mkdir /opencv_contrib/build
WORKDIR /opencv/build

RUN cmake .. -DBUILD_TIFF=ON \
             -DBUILD_opencv_java=OFF \
             -DBUILD_opencv_python2=OFF \
             -DBUILD_TEST=OFF \
             -DBUILD_PERF_TESTS=OFF \
             -DBUILD_PYTHON_SUPPORT=ON \
             -DBUILD_NEW_PYTHON_SUPPORT=ON \
             -DINSTALL_PYTHON_EXAMPLES=ON \
             -DCMAKE_BUILD_TYPE=RELEASE \
             -DCMAKE_INSTALL_PREFIX=$(python3 -c "import sys; print(sys.prefix)") \
             -DENABLE_AVX=ON \
             -DWITH_CUDA=OFF \
             -DWITH_VTK=OFF \
             -DWITH_IPP=OFF \
             -DWITH_OPENGL=ON \
             -DWITH_OPENCL=ON \
             -DWITH_TBB=ON \
             -DWITH_EIGEN=ON \
             -DWITH_V4L=ON \
             -DPYTHON3_EXECUTABLE=$(which python3) \
             -DPYTHON3_INCLUDE_DIR=$(python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") \
             -DPYTHON3_PACKAGES_PATH=$(python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")

RUN make -j4
RUN make install

